version: "3"
services:

  api:
    image: node:8-alpine
    working_dir: /app
    entrypoint: sh -c "yarn && yarn serve"
    ports:
       - 4300:4300
    volumes:
        - .:/app
    environment:
        - NODE_ENV=local
        - NO_DEMO=true
    networks:
      - c8

networks:
  c8:
